name: Security Scan
on: [push, pull_request]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Gosec
        uses: securego/gosec@master
      - name: Run Nancy
        uses: sonatype-nexus-community/nancy-github-action@main 